import { RestaurantType } from '@/types/retaurant'

export const restaurantList: Array<RestaurantType> = [
  {
    name: 'Lionel Corwin',
    distance: 6.8,
    cuisine: ['italian', 'burgers'],
    image:
      'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    isAvailable: true,
    deliveryPrice: 2,
    minBasketTotal: 2,
    opensAt: '18:50',
    rating: 5,
    deliveryTime: [10, 20],
    id: '1',
  },
  {
    name: 'Marion Reynolds',
    distance: 3.8,
    cuisine: ['italian', 'burgers'],
    image: 'https://loremflickr.com/640/480/food1',
    isAvailable: false,
    deliveryPrice: 3,
    minBasketTotal: 7,
    opensAt: '23:45',
    rating: 5,
    deliveryTime: [15, 30],
    id: '2',
  },
  {
    name: 'Wm Ward',
    distance: 6.8,
    cuisine: ['burgers'],
    image: 'https://loremflickr.com/640/480/food',
    isAvailable: true,
    deliveryPrice: 10,
    minBasketTotal: 4,
    opensAt: '17:00',
    rating: 5,
    deliveryTime: [10, 30],
    id: '3',
  },
  {
    name: 'Allen Fritsch',
    distance: 6.8,
    cuisine: ['pizza'],
    image: 'https://loremflickr.com/640/480/food2',
    isAvailable: false,
    deliveryPrice: 5,
    minBasketTotal: 5,
    opensAt: '16:30',
    rating: 5,
    deliveryTime: [20, 40],
    id: '4',
  },
  {
    name: 'Glenda Runolfsson',
    distance: 6.8,
    cuisine: ['burgers'],
    image: 'https://loremflickr.com/640/480/food3',
    isAvailable: false,
    deliveryPrice: 5,
    minBasketTotal: 1,
    opensAt: '19:30',
    rating: 4.9,
    deliveryTime: [20, 30],
    id: '5',
  },
  {
    name: 'Gina Ankunding',
    distance: 6.8,
    cuisine: ['russian'],
    image: 'https://loremflickr.com/640/480/food4',
    isAvailable: false,
    deliveryPrice: 2,
    minBasketTotal: 8,
    opensAt: '11:05',
    rating: 3.5,
    deliveryTime: [20, 40],
    id: '6',
  },
  {
    name: 'Angelo Baumbach',
    distance: 6.8,
    cuisine: ['turkish'],
    image: 'https://loremflickr.com/640/480/food5',
    isAvailable: true,
    deliveryPrice: 5,
    minBasketTotal: 8,
    opensAt: '17:15',
    rating: 4.5,
    deliveryTime: [20, 25],
    id: '7',
  },
  {
    name: 'Adrienne Bergstrom',
    distance: 6.8,
    cuisine: ['thai'],
    image: 'https://loremflickr.com/640/480/food6',
    isAvailable: true,
    deliveryPrice: 4,
    minBasketTotal: 8,
    opensAt: '13:45',
    rating: 5,
    deliveryTime: [25, 40],
    id: '8',
  },
  {
    name: 'Marlon Orn',
    distance: 6.8,
    cuisine: ['italian pizza'],
    image: 'https://loremflickr.com/640/480/food7',
    isAvailable: false,
    deliveryPrice: 5,
    minBasketTotal: 5,
    opensAt: '13:30',
    rating: 5,
    deliveryTime: [20, 40],
    id: '9',
  },
  {
    name: 'Marlon Orn',
    distance: 6.8,
    cuisine: ['italian pizza'],
    image: 'https://loremflickr.com/640/480/food7',
    isAvailable: false,
    deliveryPrice: 5,
    minBasketTotal: 5,
    opensAt: '13:30',
    rating: 5,
    deliveryTime: [20, 40],
    id: '9',
  },
]
