import { RestaurantType } from '@/types/retaurant'
export const restaurantList: Array<RestaurantType> = [
  {
    name: 'restaurant-name',
    opensAt: '17:45',
    isAvailable: false,
    rating: 4.7,
    cuisine: ['italian', 'burgers'],
    deliveryTime: [10, 20],
    distance: 6.8,
    deliveryPrice: 5.5,
    minBasketTotal: 30,
  },
  {
    name: 'restaurant-name',
    opensAt: '17:45',
    isAvailable: false,
    rating: 4.7,
    cuisine: ['italian', 'burgers'],
    deliveryTime: [10, 20],
    distance: 6.8,
    deliveryPrice: 5.5,
    minBasketTotal: 30,
  },
  {
    name: 'restaurant-name',
    opensAt: '17:45',
    isAvailable: false,
    rating: 4.7,
    cuisine: ['italian', 'burgers'],
    deliveryTime: [10, 20],
    distance: 6.8,
    deliveryPrice: 5.5,
    minBasketTotal: 30,
  },
  {
    name: 'restaurant-name',
    opensAt: '17:45',
    isAvailable: false,
    rating: 4.7,
    cuisine: ['italian', 'burgers'],
    deliveryTime: [10, 20],
    distance: 6.8,
    deliveryPrice: 5.5,
    minBasketTotal: 30,
  },
  {
    name: 'restaurant-name',
    opensAt: '17:45',
    isAvailable: false,
    rating: 4.7,
    cuisine: ['italian', 'burgers'],
    deliveryTime: [10, 20],
    distance: 6.8,
    deliveryPrice: 5.5,
    minBasketTotal: 30,
  },
]
